### ISSUE TITLE
Wrong ID label in `info_label.txt`

### ISSUE THREAD

**Issue by jcohenadad** [sct-data/sct_testing_data#9]
There are two labels ID=52:
https://github.com/spinalcordtoolbox/sct_testing_data/blob/09326204eade62907d34f1b64082adf721ed1919/mt/label/atlas/info_label.txt#L48
https://github.com/spinalcordtoolbox/sct_testing_data/blob/09326204eade62907d34f1b64082adf721ed1919/mt/label/atlas/info_label.txt#L49

The dorsal column should be 53 as per the latest PAM50 template:
https://github.com/spinalcordtoolbox/PAM50/blob/35824ab0f1bc2ecb1b4a2be59d33f5dee1105f9b/atlas/info_label.txt#L49

**Comment by joshuacwnewton** [comment]
> The dorsal column should be 53 as per the latest PAM50 template:

There is another 53, as well:

https://github.com/spinalcordtoolbox/sct_testing_data/blob/3277c4e445d53c450dd930ada84141f094405912/mt/label/atlas/info_label.txt#L48-L51

So, it looks like all labels >52 should be incremented as well:

```
 52, gray matter, 30:35 
 53, dorsal columns, 0:3 
 54, lateral funiculi, 4:13 
 55, ventral funiculi, 14:29 
```
